import { IState } from '../interfaces/StateInterface'

export const initialState: IState = {
  filter: [],
  offers: [
    {
      id: 1,
      company: 1,
      new: true,
      featured: true,
      position: 'Senior Frontend Developer',
      role: 1,
      level: 1,
      postedAt: '1d ago',
      contract: 1,
      location: 1,
      languages: [1, 2, 3],
      tools: [],
    },
    {
      id: 2,
      company: 2,
      new: true,
      featured: true,
      position: 'Fullstack Developer',
      role: 2,
      level: 2,
      postedAt: '1d ago',
      contract: 2,
      location: 2,
      languages: [4],
      tools: [1],
    },
    {
      id: 3,
      company: 3,
      new: true,
      featured: false,
      position: 'Junior Frontend Developer',
      role: 'Frontend',
      level: 3,
      postedAt: '2d ago',
      contract: 2,
      location: 1,
      languages: [3],
      tools: [1, 2],
    },
    {
      id: 4,
      company: 4,
      new: false,
      featured: false,
      position: 'Junior Frontend Developer',
      role: 1,
      level: 3,
      postedAt: '5d ago',
      contract: 2,
      location: 1,
      languages: [2, 3],
      tools: [],
    },
    {
      id: 5,
      company: 5,
      new: false,
      featured: false,
      position: 'Software Engineer',
      role: 2,
      level: 2,
      postedAt: '1w ago',
      contract: 1,
      location: 3,
      languages: [3],
      tools: [3, 2],
    },
    {
      id: 6,
      company: 6,
      new: false,
      featured: false,
      position: 'Junior Backend Developer',
      role: 3,
      level: 3,
      postedAt: '2w ago',
      contract: 1,
      location: 4,
      languages: [6],
      tools: [4],
    },
    {
      id: 7,
      company: 7,
      new: false,
      featured: false,
      position: 'Junior Developer',
      role: 1,
      level: 3,
      postedAt: '2w ago',
      contract: 1,
      location: 3,
      languages: [1, 3],
      tools: [2],
    },
    {
      id: 8,
      company: 8,
      new: false,
      featured: false,
      position: 'Junior Frontend Developer',
      role: 1,
      level: 3,
      postedAt: '2w ago',
      contract: 1,
      location: 1,
      languages: [3],
      tools: [6, 2],
    },
    {
      id: 9,
      company: 9,
      new: false,
      featured: false,
      position: 'Full Stack Engineer',
      role: 2,
      level: 2,
      postedAt: '3w ago',
      contract: 2,
      location: 3,
      languages: [3, 4],
      tools: [5],
    },
    {
      id: 10,
      company: 10,
      new: false,
      featured: false,
      position: 'Front-end Dev',
      role: 1,
      level: 3,
      postedAt: '1mo ago',
      contract: 2,
      location: 3,
      languages: [3],
      tools: [5, 2],
    },
  ],
  companies: [
    {
      id: 1,
      company: 'Photosnap',
      logo: './images/photosnap.svg',
    },
    {
      id: 2,
      company: 'Manage',
      logo: './images/manage.svg',
    },
    {
      id: 3,
      company: 'Account',
      logo: './images/account.svg',
    },
    {
      id: 4,
      company: 'MyHome',
      logo: './images/myhome.svg',
    },
    {
      id: 5,
      company: 'Loop Studios',
      logo: './images/loop-studios.svg',
    },
    {
      id: 6,
      company: 'FaceIt',
      logo: './images/faceit.svg',
    },
    {
      id: 7,
      company: 'Shortly',
      logo: './images/shortly.svg',
    },
    {
      id: 8,
      company: 'Insure',
      logo: './images/insure.svg',
    },
    {
      id: 9,
      company: 'Eyecam Co',
      logo: './images/eyecam-co.svg',
    },
    {
      id: 10,
      company: 'The Air Filter Company',
      logo: './images/the-air-filter-company.svg',
    },
  ],
  roles: [
    {
      id: 1,
      role: 'Frontend',
    },
    {
      id: 2,
      role: 'Fullstack',
    },
    {
      id: 3,
      role: 'Backend',
    },
  ],
  contracts: [
    {
      id: 1,
      contract: 'Full Time',
    },
    {
      id: 2,
      contract: 'Part Time',
    },
    {
      id: 3,
      contract: 'Contract',
    },
  ],
  levels: [
    {
      id: 1,
      level: 'Senior',
    },
    {
      id: 2,
      level: 'Midweight',
    },
    {
      id: 3,
      level: 'Junior',
    },
  ],
  locations: [
    {
      id: 1,
      location: 'USA Only',
    },
    {
      id: 2,
      location: 'Remote',
    },
    {
      id: 3,
      location: 'Worldwide',
    },
    {
      id: 4,
      location: 'UK Only',
    },
  ],
  languages: [
    {
      id: 1,
      language: 'HTML',
    },
    {
      id: 2,
      language: 'CSS',
    },
    {
      id: 3,
      language: 'JavaScript',
    },
    {
      id: 4,
      language: 'Python',
    },
    {
      id: 5,
      language: 'React',
    },
    {
      id: 6,
      language: 'Ruby',
    },
  ],
  tools: [
    {
      id: 1,
      tool: 'React',
    },
    {
      id: 2,
      tool: 'Sass',
    },
    {
      id: 3,
      tool: 'Ruby',
    },
    {
      id: 4,
      tool: 'RoR',
    },
    {
      id: 5,
      tool: 'Django',
    },
    {
      id: 6,
      tool: 'Vue',
    },
  ],
};
